# Default values for crossposter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: renatolond/mastodon-twitter-poster
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

crossposter:
  name: "pixelfed crossposter"
  hostname: crossposter.cool.tld
  repo: https://github.com/renatolond/mastodon-twitter-poster
  # twitter:
  #   client_id:
  #   client_secret:
  fedi:
    admin:
      address: ""
      user: ""
    announce:
      address: ""
      user: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: crossposter.cool.tld
      paths:
        - path: '/'
  tls:
   - secretName: crosspost-tls
     hosts:
       - crossposter.cool.tld

redis:
  cluster:
    enabled: false
  image:
    repository: bitnami/redis
    tag: 6.0.9
  usePassword: false

postgresql:
  persistence:
    enabled: true
  image:
    repository: bitnami/postgresql
    tag: 12.5.0
  postgresqlDatabase: crossposter
  # you must set a password; the password generated by the postgresql chart will
  # be rotated on each upgrade:
  # https://github.com/bitnami/charts/tree/master/bitnami/postgresql#upgrade
  postgresqlPassword: fake_db_password
  postgresqlUsername: postgres

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
