apiVersion: v1
kind: Secret
metadata:
  name: {{ template "crossposter.fullname" . }}
  labels:
    {{- include "crossposter.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASS: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"
  SECRET_KEY_BASE: "{{ randAlphaNum 32 | b64enc }}"
  TWITTER_CLIENT_ID: "{{ .Values.crossposter.twitter.client_id | b64enc }}"
  TWITTER_CLIENT_SECRET: "{{ .Values.crossposter.twitter.client_secret | b64enc }}"
